sudo: false
language: python

python:
  - "2.7"
  - "3.6"

env:
  global:
    # Use the Python version specified by Travis inside tox:
    - TOXENV=py

before_install:
  - pip install --quiet tox coveralls

  # Install Julia:
  - wget -O julia.tar.gz https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.0-linux-x86_64.tar.gz
  - tar xf julia.tar.gz
  - ln -T -s julia-*/ julia

  # Install conda:
  # https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
  #
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - ~/miniconda/bin/conda config --set always_yes yes --set changeps1 no
  - ~/miniconda/bin/conda update -q conda
  # Useful for debugging any issues with conda
  - ~/miniconda/bin/conda info -a

  - ~/miniconda/bin/conda create -q -n test python=$TRAVIS_PYTHON_VERSION pytest
  - CONDA_PIP="$HOME/miniconda/envs/test/bin/pip"
  - $CONDA_PIP install 'https://github.com/JuliaPy/pyjulia/archive/master.zip#egg=julia'
  - $CONDA_PIP install .

script:
  - export PATH="${PWD}/julia/bin:${PATH}"
  - tox -- --cov=julia_venv

  - source ~/miniconda/bin/activate test
  - julia-venv-manage install-deps
  - julia-venv-manage show
  - julia-venv -e "Base.banner(IOContext(stdout, :color => true))"
  - py.test --pyargs julia_venv

after_success:
  - .tox/py*/bin/coverage combine .coverage
  - coveralls

notifications:
  email: false
